name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: fetchhere
          repository: leejiwon1125/hello-world
      - run: ls
      - run: ls
        working-directory: ./fetchhere
        
