name: Our Workflow
on: 
  push:
  pull_request:
  
defaults:
  run:
    working-directory: ./changes

jobs:
  jobjobnamename:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: ls -al
    - run: echo The Title of your PR is ${{ github.event.pull_request.title }}
