name: Our Workflow
on: push

defaults:
 run:
  working-directory: ./changes

jobs:
  jobjobnamename:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
